name: Ubuntu

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  Ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: '^1.16.5'
    - name: build
      run: go build main.go
    - name: run
      run: ./main test/ci-test.tsp
    - name: clean
      run: rm main;
